# Generated by Django 3.1.4 on 2021-03-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='email@example.com', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
