# Generated by Django 3.1.4 on 2021-03-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='username',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
