# Generated by Django 3.1.4 on 2021-03-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_passwords_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passwords',
            new_name='Password',
        ),
    ]
