# Generated by Django 3.1.4 on 2021-03-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_auto_20210314_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='email',
        ),
        migrations.AddField(
            model_name='password',
            name='account',
            field=models.CharField(default='', max_length=100),
        ),
    ]
