# Generated by Django 3.1.4 on 2021-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0004_auto_20210314_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='account',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
