# Generated by Django 3.1.4 on 2021-03-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0005_auto_20210314_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='account',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
